name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: codewith-Ranjeet
          outputs: dist/github-contribution-grid-snake.svg?color_snake=00ffcc&color_dots=ebedf0,9be9a8,40c463,30a14e,216e39

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
